export const mockMyRequests = [
  {id : 1, name: "Đình Long", duration: 3.0 },
  {id : 2, name: "Nguyễn Văn A", duration: 7.5 },
  {id : 3, name: "Trần Thị B", duration: 8.0 },
  {id : 4, name: "Lê Hoàng C", duration: 6.75 },
  {id : 5, name: "Phạm Duy D", duration: 4.5 },
  {id : 6, name: "Hoàng Anh E", duration: 5.25 },
  {id : 7, name: "Vũ Minh F", duration: 7.0 },
  {id : 8, name: "Đào Thu G", duration: 8.0 },
  {id : 9, name: "Bùi Gia H", duration: 2.75 },
  {id : 10, name: "Ngô Hải I", duration: 6.0 },
  {id : 11, name: "Tạ Quốc J", duration: 8.0 },
  {id : 12, name: "Phan Kim K", duration: 3.25 },
  {id : 13, name: "Lương Mạnh L", duration: 5.5 },
  {id : 14, name: "Cao Mỹ M", duration: 7.75 },
  {id : 15, name: "Trịnh Quốc N", duration: 4.0 },
];
