export const mockMyRequests = [
  {
    "id": 1,
    "Date": "2025-05-01",
    "AbnormalType": "Leave Without Request",
    "RequestType": "Nghỉ Phép",
    "Status": "Submitted",
    "PartialDays": "Full Day",
  },
  {
    "id": 2,
    "Date": "2025-05-02",
    "AbnormalType": "Late Check-In",
    "RequestType": "Đi Muộn",
    "Status": "Pending",
    "PartialDays": "Morning",
  },
  {
    "id": 3,
    "Date": "2025-05-03",
    "AbnormalType": "Early Check-Out",
    "RequestType": "Về Sớm",
    "Status": "Approved",
    "PartialDays": "Afternoon",
  },
  {
    "id": 4,
    "Date": "2025-05-04",
    "AbnormalType": "No Check-In",
    "RequestType": "Xin Nghỉ",
    "Status": "Rejected",
    "PartialDays": "Full Day",
  },
  {
    "id": 5,
    "Date": "2025-05-05",
    "AbnormalType": "Leave Without Request",
    "RequestType": "Nghỉ Bệnh",
    "Status": "Cancelled",
    "PartialDays": "Morning",
  },
  {
    "id": 6,
    "Date": "2025-05-06",
    "AbnormalType": "Late Check-In",
    "RequestType": "Nghỉ Phép",
    "Status": "Submitted",
    "PartialDays": "Afternoon",
  },
  {
    "id": 7,
    "Date": "2025-05-07",
    "AbnormalType": "Early Check-Out",
    "RequestType": "Đi Công Tác",
    "Status": "Pending",
    "PartialDays": "Full Day",
  },
  {
    "id": 8,
    "Date": "2025-05-08",
    "AbnormalType": "No Check-In",
    "RequestType": "Nghỉ Phép",
    "Status": "Approved",
    "PartialDays": "Morning",
  },
  {
    "id": 9,
    "Date": "2025-05-09",
    "AbnormalType": "Late Check-In",
    "RequestType": "Xin Về Sớm",
    "Status": "Rejected",
    "PartialDays": "Afternoon",
  },
  {
    "id": 10,
    "Date": "2025-05-10",
    "AbnormalType": "Leave Without Request",
    "RequestType": "Nghỉ Bệnh",
    "Status": "Cancelled",
    "PartialDays": "Full Day",
  },
  {
    "id": 11,
    "Date": "2025-05-11",
    "AbnormalType": "Early Check-Out",
    "RequestType": "Đi Muộn",
    "Status": "Submitted",
    "PartialDays": "Morning",
  },
];
