export const mockMyRequests = [
  {
    id: 1,
    Requester: "UserA",
    RequestType: "Nghỉ Phép",
    TimeRequest: "From 2025-05-01 To 2025-05-02",
    PartialDays: "Full Day",
    DurationDays: 2,
    Status: "Submitted",
    DelegateBy: "SupervisorA",
    DelegateTo: "SupervisorB",
  },
  {
    id: 2,
    Requester: "UserB",
    RequestType: "Nghỉ Ốm",
    TimeRequest: "On 2025-05-03",
    PartialDays: "Half Day - Morning",
    DurationDays: 0.5,
    Status: "Approved",
    DelegateBy: "SupervisorB",
    DelegateTo: "SupervisorC",
  },
  {
    id: 3,
    Requester: "UserC",
    RequestType: "Công Tác",
    TimeRequest: "From 2025-05-04 To 2025-05-06",
    PartialDays: "Full Day",
    DurationDays: 3,
    Status: "Rejected",
    DelegateBy: "SupervisorA",
    DelegateTo: "SupervisorC",
  },
  {
    id: 4,
    Requester: "UserD",
    RequestType: "Nghỉ Thai Sản",
    TimeRequest: "From 2025-05-10 To 2025-08-10",
    PartialDays: "Full Day",
    DurationDays: 90,
    Status: "Submitted",
    DelegateBy: "SupervisorD",
    DelegateTo: "SupervisorE",
  },
  {
    id: 5,
    Requester: "UserE",
    RequestType: "Nghỉ Phép",
    TimeRequest: "On 2025-05-05",
    PartialDays: "Half Day - Afternoon",
    DurationDays: 0.5,
    Status: "Approved",
    DelegateBy: "SupervisorE",
    DelegateTo: "SupervisorA",
  },
  {
    id: 6,
    Requester: "UserF",
    RequestType: "Nghỉ Không Lương",
    TimeRequest: "From 2025-05-07 To 2025-05-09",
    PartialDays: "Full Day",
    DurationDays: 3,
    Status: "Submitted",
    DelegateBy: "SupervisorF",
    DelegateTo: "SupervisorB",
  },
  {
    id: 7,
    Requester: "UserG",
    RequestType: "Nghỉ Phép",
    TimeRequest: "From 2025-05-08 To 2025-05-08",
    PartialDays: "Full Day",
    DurationDays: 1,
    Status: "Approved",
    DelegateBy: "SupervisorG",
    DelegateTo: "SupervisorF",
  },
  {
    id: 8,
    Requester: "UserH",
    RequestType: "Nghỉ Phép",
    TimeRequest: "On 2025-05-09",
    PartialDays: "Half Day - Morning",
    DurationDays: 0.5,
    Status: "Submitted",
    DelegateBy: "SupervisorH",
    DelegateTo: "SupervisorG",
  },
  {
    id: 9,
    Requester: "UserI",
    RequestType: "Nghỉ Phép",
    TimeRequest: "From 2025-05-11 To 2025-05-12",
    PartialDays: "Full Day",
    DurationDays: 2,
    Status: "Rejected",
    DelegateBy: "SupervisorI",
    DelegateTo: "SupervisorJ",
  },
  {
    id: 10,
    Requester: "UserJ",
    RequestType: "Nghỉ Phép",
    TimeRequest: "On 2025-05-13",
    PartialDays: "Full Day",
    DurationDays: 1,
    Status: "Submitted",
    DelegateBy: "SupervisorJ",
    DelegateTo: "SupervisorI",
  },
  {
    id: 11,
    Requester: "UserK",
    RequestType: "Nghỉ Ốm",
    TimeRequest: "From 2025-05-14 To 2025-05-15",
    PartialDays: "Full Day",
    DurationDays: 2,
    Status: "Approved",
    DelegateBy: "SupervisorK",
    DelegateTo: "SupervisorL",
  },
  {
    id: 12,
    Requester: "UserL",
    RequestType: "Nghỉ Phép",
    TimeRequest: "From 2025-05-16 To 2025-05-20",
    PartialDays: "Full Day",
    DurationDays: 5,
    Status: "Pending",
    DelegateBy: "SupervisorL",
    DelegateTo: "SupervisorM",
  },
  {
    id: 13,
    Requester: "UserM",
    RequestType: "Công Tác",
    TimeRequest: "From 2025-05-18 To 2025-05-19",
    PartialDays: "Full Day",
    DurationDays: 2,
    Status: "Submitted",
    DelegateBy: "SupervisorM",
    DelegateTo: "SupervisorN",
  },
  {
    id: 14,
    Requester: "UserN",
    RequestType: "Nghỉ Phép",
    TimeRequest: "On 2025-05-21",
    PartialDays: "Half Day - Afternoon",
    DurationDays: 0.5,
    Status: "Rejected",
    DelegateBy: "SupervisorN",
    DelegateTo: "SupervisorO",
  },
  {
    id: 15,
    Requester: "UserO",
    RequestType: "Nghỉ Phép",
    TimeRequest: "From 2025-05-22 To 2025-05-23",
    PartialDays: "Full Day",
    DurationDays: 2,
    Status: "Approved",
    DelegateBy: "SupervisorO",
    DelegateTo: "SupervisorP",
  },
];
